### ISSUE TITLE
Problem running python files

### ISSUE THREAD

**Issue by parasit** [arjunmahishi/run-code.nvim#7]
Hi,
I'm not sure where problem is but when i try to run some python code in neovim got error:
```
zsh:1: command not found: python
```
But i have python (3.10), alias in `~/.zshrc` `alias python=python3` and it works fine... except with your plugin. 

P.S. With enabled virtualenv everything is ok... super strange.

**Comment by arjunmahishi** [comment]
Hey @parasit, thanks for reaching out. I am aware of this issue, just haven't gotten around to fixing it yet. This happens because, the aliases that you set are not inherited into vim's shell session. So, only commands that are available on the run time path can be used. 

**For now, there are two ways to solve this**
1. Instead of an alias, create a file called `python` in your run time path with the following contents and make it executable. (works for me)
```bash
#!/bin/bash

python3 $@
```
2. The other alternative is to use the custom commands feature. This is still an experimental feature and I am still working on the documentation for it. So, I would suggest to go with the 1st method.

**Comment by fennelcakes** [comment]
Is there a way to do this with the custom commands now that there's a more streamlined integration with Telescope? I'm on MacOS and  I think because of the restrictions preventing any writing to /bin, I can't get method #1 you suggested above to work.

I tried creating a custom command with `python3` but I don't know how to pass the current Nvim file to the custom command (`%` doesn't work like it does in the vim command line, expectedly).

**Comment by arjunmahishi** [comment]
Hey @fennelcakes,

Yes, you can absolutely do this with custom commands!

> I tried creating a custom command with python3 but I don't know how to pass the current Nvim file to the custom command (% doesn't work like it does in the vim command line, expectedly).

Check out the [custom variables](https://github.com/arjunmahishi/run-code.nvim#custom-variables) section in the README. There is a variable called `curr_file` which is available to you as an environment variable to use in the custom command. You can use it like this:

```bash
python3 $curr_file
``` 

Hope this helps :)
